name: docker
version: 1.3.3.002-1
architecture: amd64
icon: meta/docker.svg
vendor: Pierre-Andre MOREY <pierre-andre.morey@canonical.com>
type: framework
services:
  - name: docker
    description: The docker app deployment mechanism
    start: bin/docker.start
    stop: bin/docker.stop
    poststop: bin/docker.poststop
binaries:
  - name: bin/docker
    security-policy: docker_docker_1.3.3.002-1
  - name: bin/docker-privilege
integration:
  framework:
    framework: meta/docker.framework
  docker:
    apparmor-profile: meta/docker-daemon.profile
