name: docker
version: 1.11.2-1
architectures: [amd64, armhf]
icon: meta/docker.svg
vendor: Pierre-Andre MOREY <pierre-andre.morey@canonical.com>
type: framework
services:
  - name: docker-daemon
    description: The docker app deployment mechanism
    start: bin/docker-daemon
    security-policy:
      apparmor: meta/docker-daemon.apparmor
      seccomp: meta/docker-daemon.seccomp
binaries:
  - name: bin/docker
    caps:
      - docker_client
      - network-client
  - name: bin/docker-privilege
    security-policy:
      apparmor: meta/docker-privilege.apparmor
      seccomp: meta/docker-privilege.seccomp
