name: com.ubuntu.snappy.docker
version: 1.3.2.001
architecture: amd64
icon: meta/docker.svg
maintainer: Pierre-Andre MOREY <pierre-andre.morey@canonical.com>
frameworks: ubuntu-core-15.04-dev1
services:
  - name: docker
    description: Docker framework for snappy
    start: bin/docker.wrap
integration:
  cli:
     bin-path: bin/docker
  framework:
    framework: meta/docker.framework
  daemon:
    apparmor-profile: meta/docker-daemon.profile
