name: docker
version: 1.3.2.005
architecture: amd64
icon: meta/docker.svg
vendor: Pierre-Andre MOREY <pierre-andre.morey@canonical.com>
frameworks: ubuntu-core-15.04-dev1
services:
  - name: docker
    description: The docker app deployment mechanism
    start: bin/docker.wrap
integration:
  cli:
     bin-path: bin/docker
  framework:
    framework: meta/docker.framework
  docker:
    apparmor-profile: meta/docker-daemon.profile
