name: docker
version: 1.3.3.002-2
architecture: amd64
icon: meta/docker.svg
vendor: Pierre-Andre MOREY <pierre-andre.morey@canonical.com>
type: framework
services:
  - name: docker-daemon
    description: The docker app deployment mechanism
    start: bin/docker.start
    stop: bin/docker.stop
    poststop: bin/docker.poststop
    security-policy:
      apparmor: meta/docker-daemon.apparmor
      seccomp: meta/docker-daemon.seccomp
binaries:
  - name: bin/docker
    caps:
      - docker_client
      - networking
  - name: bin/docker-privilege
