name: docker
version: 1.3.3.002
architecture: amd64
icon: meta/docker.svg
vendor: Pierre-Andre MOREY <pierre-andre.morey@canonical.com>
type: framework
services:
  - name: docker
    description: The docker app deployment mechanism
    start: bin/docker.start
    stop: bin/docker.stop
    poststop: bin/docker.poststop
integration:
  framework:
    framework: meta/docker.framework
  docker:
    apparmor-profile: meta/docker-daemon.profile
    bin-path: bin/docker
  docker-privilege:
    bin-path: bin/docker-privilege

